name: Deploy Frontend
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t iulianbuzdugan/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true iulianbuzdugan/docker-react npm test

      - run: docker build -t iulianbuzdugan/multi-client-hga ./client
      - run: docker build -t iulianbuzdugan/multi-nginx-hga ./nginx
      - run: docker build -t iulianbuzdugan/multi-server-hga ./server
      - run: docker build -t iulianbuzdugan/multi-worker-hga ./worker

      - run: docker push iulianbuzdugan/multi-client-hga
      - run: docker push iulianbuzdugan/multi-nginx-hga
      - run: docker push iulianbuzdugan/multi-server-hga
      - run: docker push iulianbuzdugan/multi-worker-hga
